- src/am_map.cpp
- src/common/2d/v_2ddrawer.cpp
- src/common/cutscenes/screenjob.cpp
- src/common/menu/menu.cpp
- src/common/rendering/hwrenderer/data/hw_cvars.cpp
- src/common/startscreen/endoom.cpp
- src/common/statusbar/base_sbar.cpp
- src/d_netinfo.cpp
- src/g_cvars.cpp
- src/g_game.cpp
- src/g_statusbar/shared_sbar.cpp
- src/playsim/p_mobj.cpp
- src/rendering/hwrenderer/scene/hw_lighting.cpp
- src/rendering/hwrenderer/scene/hw_sprites.cpp
- wadsrc/static/menudef.txt
- Show item counter on automap
- Enable thicker automap lines and anti-aliased lines for better visibility with high res displays
- Enable textured automap
- HUD border scaling factor to better match default status bar scaling
- Enable subtitles
- Set render quality to "quality" to fix level mesh seams (gl_seamless)
- Enable mouse in menus by default (instead of touchscreen-like)
- Don't show ENDDOOM when quitting the app
- Enable the first crosshair, and set its scale slightly smaller
- Grow crosshair when picking up items
- Set autoaim slider to 0
- Show nametags when switching items and weapons
- Always run enabled
- Disable save/load confirmation dialog
- Enable quicksave rotation
- Enable additively-translucent Doom rocket explosion
- Increase default particles to 10k, and increase …
> Change more default settings 

- wadsrc/static/language.def
- wadsrc/static/menudef.txt
Better have them in the proper place right away instead of mixing string types in menudef.txt
> moved all newly added menu strigs to the string table.

- src/g_level.cpp
- src/gamedata/g_mapinfo.cpp
- src/gamedata/g_mapinfo.h
- wadsrc/static/zscript/constants.zs
This fully disables autosaves when a map is just entered (ignoring the user's autosave preference).
There are some legitimate use cases where a modder might want to set a map up to not autosave upon entry. Perhaps said map was intended to be some intermediary non-gameplay map.
Example file specifically disables autosave-upon-entry for Doom 2 MAP02: [NoAutosaveOnEnter.zip](https://github.com/dpjudas/VkDoom/files/12061774/NoAutosaveOnEnter.zip)
> Add MAPINFO NoAutoSaveOnEnter

- src/common/2d/wipe.cpp
- src/common/rendering/vulkan/samplers/vk_samplers.cpp
- src/common/rendering/vulkan/samplers/vk_samplers.h
- src/common/rendering/vulkan/textures/vk_hwtexture.cpp
- src/common/textures/gametexture.h
- src/common/textures/hw_material.cpp
- src/common/textures/hw_material.h
- src/r_data/gldefs.cpp
- src/rendering/swrenderer/r_swscene.cpp
~~It works, but I don't like the implementation.~~
~~Also: I think it should match the mipmap settings of the current texture filtering.~~
Update: Refactored. I'm more fond of this implementation.
As for GLDefs, it looks like this:
```cpp
material "asdf" {
Shader "..."
// ... etc
texture tex_height "cliff_lh" { filter linear }
}
```
> Initial implementation of the customizable layer filtering

- src/common/rendering/hwrenderer/data/hw_levelmesh.h
- src/common/rendering/vulkan/accelstructs/vk_lightmap.cpp
- src/common/rendering/vulkan/vk_renderdevice.cpp
- src/rendering/hwrenderer/doom_levelmesh.cpp
- src/rendering/hwrenderer/doom_levelmesh.h
Now it runs the lightmapper, downloads the output and copies it onto the texture atlas.
The issues are:
1. the buffers the lightmapper shader uses aren't filled... (Maybe?)
2. the lightmapper runs every frame.
> Fix bugs and copy lightmapper output to the atlas

- src/common/rendering/hwrenderer/data/hw_levelmesh.h
- src/common/rendering/hwrenderer/data/hw_renderstate.h
- src/common/rendering/v_video.h
- src/common/rendering/vulkan/accelstructs/vk_lightmap.cpp
- src/common/rendering/vulkan/accelstructs/vk_lightmap.h
- src/common/rendering/vulkan/vk_renderdevice.cpp
- src/common/rendering/vulkan/vk_renderdevice.h
- src/rendering/hwrenderer/doom_levelmesh.cpp
- src/rendering/hwrenderer/doom_levelmesh.h
- src/rendering/hwrenderer/hw_entrypoint.cpp
- src/rendering/hwrenderer/hw_vertexbuilder.cpp
- src/rendering/hwrenderer/scene/hw_bsp.cpp
- src/rendering/hwrenderer/scene/hw_flats.cpp
- src/rendering/hwrenderer/scene/hw_walls.cpp
*Now with less WTF temporary hack code I overlooked by accident*
Allows for partial lightmap updates. The lightmapper has high priority for surfaces visible on screen, otherwise it runs "background tasks" updating handful of surfaces that need updating.
CVARs:
**lm_scale** - multiplier for lightmap resolution of every surface. There is a hardcoded bottom limit of 0.25
**lm_background_updates 8** - How many lightmap surfaces should be progressed in the background per frame
**lm_max_updates 128** - How many on-screen surfaces can be updated per frame
CCMDs:
invalidatelightmaps
stat lightmapper
> Partial Lightmapper

- src/common/rendering/hwrenderer/data/hw_levelmesh.h
- src/common/rendering/hwrenderer/data/hw_renderstate.h
- src/common/rendering/vulkan/accelstructs/vk_lightmap.cpp
- src/rendering/hwrenderer/doom_levelmesh.cpp
- src/rendering/hwrenderer/scene/hw_bsp.cpp
Skip sky, obviously unlit surfaces and check whether the pointlight is in front of the surface or not before adding it to the light list.
> Optimize which surfaces are passed to lightmapper

- src/rendering/hwrenderer/doom_levelmesh.cpp
- src/rendering/hwrenderer/doom_levelmesh.h
- src/rendering/hwrenderer/scene/hw_flats.cpp
I tried to find a more proper way, but that didn't work. It's a "temporary" workaround.
> Workaround to make 3d floor side surfaces detectable

- src/common/rendering/hwrenderer/data/hw_levelmesh.h
- src/common/rendering/vulkan/accelstructs/vk_lightmap.cpp
- src/rendering/hwrenderer/doom_levelmesh.cpp
`stat lightmap` shows general statistics involving the lightmap.
`stat lightmapper` now also shows pixel area statistics.
`surfaceinfo` fires ray from player's pov against the levelmesh and prints information about which surface the ray hit.
> Bunch of lightmap stats and ccmds

- src/common/rendering/hwrenderer/data/hw_skydome.cpp
The lightmap index was uninitialized in the vertices.
> Fix sky dome getting randomly influenced by the lightmaps

- src/maploader/maploader.cpp
- src/maploader/maploader.h
- src/rendering/hwrenderer/doom_levelmesh.cpp
- src/rendering/hwrenderer/doom_levelmesh.h
- src/rendering/hwrenderer/scene/hw_drawinfo.h
The optimization replaces linear search with TMap.
The fix for the mismatch in surface size is "use whatever surface size ZDRay came up with" and pack the lightmap atlas after the surfaces are modified.
> Optimize and fix surface mismatch errors

- src/common/rendering/hwrenderer/data/hw_levelmesh.h
- src/common/rendering/vulkan/accelstructs/vk_lightmap.cpp
- src/common/rendering/vulkan/accelstructs/vk_raytrace.cpp
- src/common/rendering/vulkan/accelstructs/vk_raytrace.h
- src/gamedata/r_defs.h
- src/rendering/hwrenderer/doom_levelmesh.cpp
- src/rendering/hwrenderer/doom_levelmesh.h
- src/rendering/hwrenderer/scene/hw_drawstructs.h
- src/rendering/hwrenderer/scene/hw_flats.cpp
- src/rendering/hwrenderer/scene/hw_walls.cpp
- wadsrc/static/shaders/lightmap/frag_raytrace.glsl
The levelmesh wall surfaces are usually misaligned with HWWall.
Floors and ceilings should be accurate.
I didn't try 3D floors, I assume they just don't work correctly without crashing.
There are still many quirks and bugs to fix (front+back surfaces of the textures are stuck together which is responsible for random visual artefacts)
Note that the light blending is very WIP and the formula will change.
> Raytrace alpha and color blending

- src/rendering/hwrenderer/scene/hw_walls.cpp
- wadsrc/static/shaders/lightmap/frag_raytrace.glsl
uses a simplified Beer–Lambert law... not sure if correctly, but it looks nicer.
(blue, red+green light, white light)
Here's the **old version**:
Now the surface absorbs the colored light:
> Better mid-texture color blending

- src/common/rendering/vulkan/vk_levelmesh.cpp
The compilation failed because there was more than one vk_rayquery variable (A CVAR and a hard-coded global true value), so I removed the latter.
> Attempt to fix compilation errors on other platforms

- src/r_data/gldefs.cpp
`MaterialLayerSampling::Default` is `-1`, so the `{ }` initialization of `MaterialLayers` sets it incorrectly to 0 which is `MaterialLayerSampling::Nearest`
> Fix shader custom texture filtering not set to default by default

- src/rendering/hwrenderer/scene/hw_spritelight.cpp
When applying tracelights onto actors, both 3D levelmesh and 2D shadowmap are tested.
To my knowledge checking 2D shadowmap is basically redundant and causes extreme slowdowns when many sprites are tested against many tracelights.
Before (30 FPS max):
After (196 FPS max):
> Fix redundant 2D shadowmap test for lightmap lights

- src/rendering/hwrenderer/scene/hw_spritelight.cpp
Turns out particles do not use levelmesh but 2D shadowmapping only for tracelights. This restores that behavior.
> Fix: Apply 2D shadowmapping to particles

- wadsrc/static/shaders/scene/lightmodel_specular.glsl
For a long time now specular materials have not been able to have their glossiness and level changed outside of the initial GLDEFS and within a custom shader file definition due to an oversight in their underlying shader code. This pull request fixes that.
- Ashley (Dark Assassin)
> Fix Specular not using Material definition for Glossiness and Level

- src/rendering/hwrenderer/scene/hw_drawinfo.cpp
Example file:
[CoronaBugTest.zip](https://github.com/user-attachments/files/17001609/CoronaBugTest.zip)
> Fix broken corona when the sprite contains alpha

- src/common/rendering/hwrenderer/data/hw_lightmaptile.h
- src/common/rendering/vulkan/vk_lightmapper.cpp
- src/rendering/hwrenderer/doom_levelmesh.cpp
- src/rendering/hwrenderer/doom_levelmesh.h
- src/rendering/hwrenderer/scene/hw_drawinfo.h
- src/rendering/hwrenderer/scene/hw_spritelight.cpp
Allows disabling of this feature via `lm_dynamic` for lower end hardware so they can continue to make use of the lightmaps without having to outright disable them. This may provide some lighting issues here and there but ultimately beats having to disable the lightmap in its entirety should someone make only sparse use of the feature in their map.
> Added toggle for lm_dynamic sectors

- src/common/utility/tarray.h
- src/playsim/a_dynlight.cpp
- src/playsim/a_dynlight.h
- src/playsim/actor.h
- src/rendering/hwrenderer/scene/hw_spritelight.cpp
isn't the fastest or most memory efficient fix, but should hopefully only be temporary
> Fix cache while trace isn't moved to GPU

- src/common/rendering/hwrenderer/postprocessing/hw_useruniforms.h
- src/common/rendering/vulkan/shaders/vk_shader.cpp
- src/common/rendering/vulkan/shaders/vk_shader.h
- src/common/textures/textures.h
- src/r_data/gldefs.cpp
```
varing [noperspective|flat] <type> <name>
```
> add in/out varyings to materials/globalshaders in gldefs

- src/playsim/a_dynlight.cpp
Fixed released lights not unlinking in rare cases. Fixed first Actor in cache being missed when destruction checking. Fixed results cache not being cleared on update.
> Fixes for dynamic lights

- src/common/platform/posix/sdl/i_input.cpp
previously mouse handling was a bit wonky on linux because clicking would make the cursor disappear (since it got put into relative mode for some reason), which i was able to ignore but for some reason now on my system clicking makes the mouse cursor jump to weird places on the screen.
so this makes the mouse handling work more like the windows backend, doesn't seem to break anything from my testing
> improve SDL mouse handling in menus

- src/common/models/bonecomponents.h
- src/common/models/model.h
- src/common/models/model_iqm.h
- src/common/models/model_kvx.h
- src/common/models/model_md2.h
- src/common/models/model_md3.h
- src/common/models/model_obj.h
- src/common/models/model_ue1.h
- src/common/models/modelrenderer.h
- src/common/models/models_iqm.cpp
- src/common/models/models_md2.cpp
- src/common/models/models_md3.cpp
- src/common/models/models_obj.cpp
- src/common/models/models_ue1.cpp
- src/common/models/models_voxel.cpp
- src/playsim/actor.h
- src/playsim/p_actionfunctions.cpp
- src/playsim/p_mobj.cpp
- src/r_data/models.cpp
- src/rendering/hwrenderer/hw_models.cpp
- src/rendering/hwrenderer/hw_models.h
This is a port of [this cleanup work from GZDoom](https://github.com/ZDoom/gzdoom/commit/3d2f9e06ed39c664ce4e387a74c26706d7f928cc), but with VKDoom-specific adjustments.
I'm making this as a PR, instead of committing directly to master, to let it sit for a bit (and do some more testing) before merging it proper.
> Remove bone component cache

- src/common/rendering/hwrenderer/data/hw_cvars.cpp
- src/common/rendering/hwrenderer/data/hw_cvars.h
- src/common/rendering/hwrenderer/data/hw_viewpointuniforms.h
- src/common/rendering/vulkan/shaders/vk_shader.cpp
- src/common/rendering/vulkan/shaders/vk_shader.h
- src/common/rendering/vulkan/vk_renderstate.cpp
- src/common/utility/vectors.h
- src/rendering/hwrenderer/scene/hw_drawinfo.cpp
- wadsrc/static/menudef.txt
- wadsrc/static/shaders/lightmap/polyfill_rayquery.glsl
- wadsrc/static/shaders/scene/binding_rsbuffers.glsl
- wadsrc/static/shaders/scene/light_trace.glsl
it needs to trace twice and run logic to find the closest hit (if any) that's facing the camera, so it's off by default
> add camera-facing midtexture shadows to dynamic lights, off by default due to fps hit

- src/CMakeLists.txt
- src/common/rendering/hwrenderer/data/hw_lightprobe.cpp
- src/common/rendering/hwrenderer/data/hw_lightprobe.h
- src/common/rendering/v_video.h
- src/common/rendering/vulkan/textures/vk_texture.cpp
- src/common/rendering/vulkan/textures/vk_texture.h
- src/common/rendering/vulkan/vk_lightprober.cpp
- src/common/rendering/vulkan/vk_lightprober.h
- src/common/rendering/vulkan/vk_renderdevice.cpp
- src/common/rendering/vulkan/vk_renderdevice.h
- src/gamedata/r_defs.h
- src/namedef_custom.h
- src/p_setup.cpp
- src/rendering/hwrenderer/doom_lightprobes.cpp
- src/rendering/hwrenderer/hw_entrypoint.cpp
- src/rendering/hwrenderer/scene/hw_flats.cpp
- src/rendering/hwrenderer/scene/hw_walls.cpp
- wadsrc/static/shaders/scene/lightmodel_pbr.glsl
- wadsrc/static/zscript.txt
- wadsrc/static/zscript/actors/shared/lightprobe.zs
Support one probe bound per side_t and sector_t (TODO: more individual pieces?)
Render cubemap per frame into buffer, before uploading as single continuous blob.
Placeholder "LightProbe" object used as viewpoint for rendering (not what it was meant for, but I needed something)
`addlightprobe` adds a probe and recalculates updates probe binding
`dumplightprobes` shows where are the probes
`dumplightprobetargets` lists which side and sector uses which probe
`autoaddlightprobes` will place lightprobes roughly at the centerpoint of all sectors (naive solution)
`gl_lightprobe 1` will keep re-rendering the probes
> Lightprobe WIP part 2

- src/common/rendering/vulkan/pipelines/vk_renderpass.cpp
- src/common/rendering/vulkan/pipelines/vk_renderpass.h
Fixes nullptr exception when switching to `gl_ubershaders 0`
Thread count is `std::thread::hardware_concurrency() / 2` threads (or overriden by `vk_pipeline_threads`) clamped between `1` and `std::thread::hardware_concurrency() - 2 - int(gl_multithread != 0)`
**Thread work isn't equally distributed, that may need further rework of the code.**
Fixes missing include for Linux/macOSS
> More Worker Threads For Specialized Shader Compilation

- src/common/rendering/hwrenderer/data/hw_dynlightdata.h
~~buffer should still be only 2~3mb, not a concern vram-wise, and not even close to the 128mb minimum supported size for storage buffers~~ changed limit to 80k to match gzdoom
> changed light limit to 80k to match gzdoom

- src/rendering/hwrenderer/scene/hw_flats.cpp
- src/rendering/hwrenderer/scene/hw_portal.cpp
- src/rendering/hwrenderer/scene/hw_sky.cpp
Non-levelmesh artifacts in stacked-sector portals and planemirrors.
See: https://github.com/ZDoom/gzdoom/pull/3183
vkdoom-centric version. 
Load maps and look down.
[visual_bug_floormaps.zip](https://github.com/user-attachments/files/21093204/visual_bug_floormaps.zip)
> Squashing a visual rendering bug in stacked sector portals
