dpjudas/VkDoom

src/common/engine/serializer.cpp
src/common/objects/dobjtype.cpp
src/common/scripting/vm/vm.h
src/common/utility/vectors.h
src/playsim/p_pspr.cpp
src/playsim/p_tags.cpp
src/playsim/p_tags.h
src/rendering/hwrenderer/scene/hw_weapon.cpp
src/scripting/thingdef_data.cpp
src/scripting/vmthunks.cpp
wadsrc/static/zscript/actors/inventory/inventory.zs
wadsrc/static/zscript/actors/inventory/weapons.zs
wadsrc/static/zscript/mapdata.zs

https://github.com/ZDoom/gzdoom/pull/1953
https://github.com/ZDoom/gzdoom/pull/1986
https://github.com/ZDoom/gzdoom/pull/1990
https://github.com/ZDoom/gzdoom/pull/2002

multiple of my PRs from gzdoom rolled into one

---

src/rendering/hwrenderer/doom_levelmesh.cpp
src/rendering/hwrenderer/doom_levelmesh.h

I've made these enhancement in hopes of finding anything that could be wrong.
well, I didn't, but anyway:
Each surface is its own object
Each has label as to which surface it is and whether or not it is sky.

Enhance dumplevelmesh

---

src/rendering/hwrenderer/doom_levelmesh.cpp

Fix the lightmapper ceiling/floor plane calculations

---

src/common/rendering/hwrenderer/data/hw_levelmesh.h
src/common/rendering/vulkan/accelstructs/vk_raytrace.cpp
src/maploader/maploader.cpp
src/rendering/hwrenderer/doom_levelmesh.cpp
src/rendering/hwrenderer/doom_levelmesh.h

Rays can now pass through sector/line portals.

Lightmapper Sector/Line portals

---

src/common/rendering/hwrenderer/data/hw_levelmesh.h
src/common/rendering/vulkan/accelstructs/vk_lightmap.cpp
src/rendering/hwrenderer/doom_levelmesh.cpp
src/rendering/hwrenderer/doom_levelmesh.h
src/rendering/hwrenderer/scene/hw_spritelight.cpp

Port of ZDRay portal light list propagation and support for tracelight portals in VKDoom
I'll be doing more testing in the meantime.

Lightmapper portal pointlights

---

src/rendering/hwrenderer/hw_vertexbuilder.cpp

No more holes popping up in the floors/ceilings for weirder sectors.

Fix CreateIndexedSectorVerticesLM

---

src/common/rendering/vulkan/accelstructs/vk_raytrace.cpp
src/common/rendering/vulkan/vk_renderdevice.cpp
src/p_setup.cpp
src/rendering/hwrenderer/hw_entrypoint.cpp

Remove hacks associated with SetLevelMesh

---

src/common/rendering/hwrenderer/data/hw_levelmesh.h
src/common/rendering/vulkan/textures/vk_texture.cpp
src/common/rendering/vulkan/textures/vk_texture.h
src/common/rendering/vulkan/vk_renderdevice.cpp
src/maploader/maploader.cpp
src/maploader/maploader.h
src/maploader/udmf.cpp
src/rendering/hwrenderer/doom_levelmesh.cpp
src/rendering/hwrenderer/doom_levelmesh.h
src/rendering/hwrenderer/scene/hw_flats.cpp

Add support to load version 1 of lightmap lump.
Also adds cvar `genlightmaps` to run internal lightmapper in maps where lightmaps aren't used.

Lightmap lump loading and genlightmaps cvar

---

src/common/rendering/hwrenderer/data/hw_levelmesh.h
src/maploader/maploader.cpp
src/rendering/hwrenderer/doom_levelmesh.cpp

ZDRay PR: https://github.com/ZDoom/ZDRay/pull/54

Lightmap lump v2

---

wadsrc/static/shaders/lightmap/vert_raytrace.glsl

Fix lights being slightly shifted

---

src/rendering/hwrenderer/scene/hw_spritelight.cpp
wadsrc/static/shaders/lightmap/trace_sunlight.glsl

Fixes sunlight issues in my huge open maps

Increase and unify max distance for sunlight rays

---

src/rendering/hwrenderer/scene/hw_sprites.cpp
wadsrc/static/shaders/scene/fogball.glsl

Convert fogball calculations from sRGB to linear

---

src/common/rendering/hwrenderer/data/hw_meshbuilder.cpp
src/gamedata/r_defs.h
src/levelmeshhelper.h
src/playsim/p_map.cpp
src/scripting/vmthunks.cpp

This will require some follow ups later to track Texture UV changes and to track when to use shaders.

Notify Level Mesh of updates (first phase)

---

specs/udmf_zdoom.txt
src/common/rendering/hwrenderer/data/hw_renderstate.h
src/common/rendering/hwrenderer/data/hw_viewpointuniforms.h
src/common/rendering/vulkan/shaders/vk_shader.cpp
src/common/rendering/vulkan/shaders/vk_shader.h
src/common/rendering/vulkan/vk_renderstate.cpp
src/doomdata.h
src/gamedata/g_mapinfo.cpp
src/gamedata/g_mapinfo.h
src/maploader/udmf.cpp
src/namedef_custom.h
src/playsim/a_dynlight.cpp
src/playsim/a_dynlight.h
src/playsim/actor.h
src/playsim/p_mobj.cpp
src/r_data/a_dynlightdata.cpp
src/rendering/hwrenderer/hw_dynlightdata.cpp
src/rendering/hwrenderer/scene/hw_drawinfo.cpp
src/rendering/hwrenderer/scene/hw_spritelight.cpp
wadsrc/static/shaders/scene/binding_rsbuffers.glsl
wadsrc/static/shaders/scene/lightmodel_normal.glsl
wadsrc/static/shaders/scene/lightmodel_pbr.glsl
wadsrc/static/shaders/scene/lightmodel_shared.glsl
wadsrc/static/shaders/scene/lightmodel_specular.glsl
wadsrc/static/zscript/actors/shared/dynlights.zs

ex.:
```
LightAttenuationMode = "Default"
LightAttenuationMode = "Linear"
LightAttenuationMode = "InverseSquare"
```

Allow setting light attenuation mode from mapinfo

---

src/gamedata/r_defs.h
src/playsim/p_trace.cpp

Prevent dummy trace sectors from sending updates to the accel struct

3D floor performance fix

---

src/common/rendering/hwrenderer/data/hw_collision.cpp
src/gamedata/decallib.cpp
src/playsim/a_decals.cpp
src/rendering/hwrenderer/doom_levelmesh.cpp

Only update the mesh if a decal was actually attached to a side

Cleaned up decal behavior

---

src/rendering/hwrenderer/hw_entrypoint.cpp
src/rendering/hwrenderer/scene/hw_drawinfo.cpp
src/rendering/hwrenderer/scene/hw_drawinfo.h
src/rendering/hwrenderer/scene/hw_sprites.cpp

Take sector portals into account for fogballs and make coronas work through portals/cam textures

Updated fogball/corona portal behavior

---

src/common/console/c_cvars.cpp
src/common/console/c_cvars.h
src/common/rendering/hwrenderer/postprocessing/hw_postprocess.cpp
src/common/rendering/hwrenderer/postprocessing/hw_postprocessshader.cpp
src/common/rendering/hwrenderer/postprocessing/hw_postprocessshader.h
src/r_data/gldefs.cpp
wadsrc/static/zscript/engine/ppshader.zs

cvar uniform example:
```
uniform float example_strength = cvar cvar_example
uniform vec3 example_color = cvar cvar_example2
```
default value example:
```
uniform vec3 example_color = 1.0 0.5 0.5
```

add default values, vec4 uniforms, and cvar uniforms to post-process uniforms

---

src/common/rendering/hwrenderer/postprocessing/hw_postprocess.cpp

(remove legacy opengl bullshit)

stop crash with vec3 uniforms

---

src/rendering/hwrenderer/scene/hw_drawinfo.h
src/rendering/hwrenderer/scene/hw_spritelight.cpp
src/rendering/hwrenderer/scene/hw_sprites.cpp
src/rendering/hwrenderer/scene/hw_weapon.cpp

the light list was only getting added for actors

fix lights on vts

---

src/rendering/hwrenderer/scene/hw_spritelight.cpp

(don't collect lights for fullbright particles/vts)

add missing check

---

src/common/rendering/vulkan/textures/vk_texture.cpp
src/common/rendering/vulkan/vk_lightprober.cpp

I'm too tired to actually understand what sort of difference I actually made here aside from it not being broken anymore...

Fix upload of prefilterred maps

---

src/maploader/maploader.cpp
src/rendering/hwrenderer/doom_levelmesh.cpp
src/rendering/hwrenderer/scene/hw_drawstructs.h

Doesn't change any functionality.

Minor refactor of lightmap loading code

---

src/common/rendering/vulkan/pipelines/vk_renderpass.cpp
wadsrc/static/shaders/scene/light_shadow.glsl

First commit optimizes ubershader compilation from ~30 seconds to ~9 seconds.
It also cleans up `#if`s which are always true.
Second commit adds simple utility to print and show the creation time (for my convenience)
and non-archived dev/debug cvars `gl_ubershaders` and `vk_debug_pipeline_creation` for more convenience.

Optimize Ubershader + Utils

---

src/common/rendering/vulkan/pipelines/vk_renderpass.cpp

Fix missing incrementation of pipeline counter for stat pipelines.

---

src/common/rendering/vulkan/pipelines/vk_renderpass.cpp

Fix Pipeline Library Generalized Shaders 

---

src/common/rendering/vulkan/shaders/vk_shader.cpp

Fix Shader Light Attenuation

---

wadsrc/static/shaders/scene/light_trace.glsl

Uses a 4x4 dither effect for `gl_light_shadow_filter 0` to support soft shadow radius.

SoftShadowRadius for 1 sample RT lights via dithering effect

---

src/common/rendering/vulkan/pipelines/vk_renderpass.cpp
src/common/rendering/vulkan/pipelines/vk_renderpass.h

Wait... you have to check an extra boolean to know if the extension is actually supported?! What were they thinking?!

Add Fallback For Pipeline Creation

---

src/common/engine/serializer.h
src/common/models/bonecomponents.h
src/common/models/model.cpp
src/common/models/model.h
src/common/models/model_iqm.h
src/common/models/models_iqm.cpp
src/common/utility/TRS.h
src/common/utility/matrix.cpp
src/common/utility/matrix.h
src/common/utility/quaternion.h
src/playsim/actor.h
src/playsim/p_actionfunctions.cpp
src/playsim/p_mobj.cpp
src/r_data/models.cpp
src/r_data/models.h
src/rendering/hwrenderer/hw_precache.cpp
src/version.h
wadsrc/static/zscript.txt
wadsrc/static/zscript/actors/actor.zs
wadsrc/static/zscript/constants.zs

merging early due to differences in model.cpp between gzdoom and vkdoom

Bone manip part1

---

src/playsim/p_actionfunctions.cpp
src/r_data/models.cpp

the new code didn't quite work with A_SetModel modeldef changes, this fixes that

fix CalcModelFrame/SetBone/GetBone/SetAnimation not grabbing smf from modeldata for decoupled anims

---

src/r_data/models.cpp

fix MDL_USEROTATIONCENTER

---

src/playsim/a_dynlight.cpp

because of fucking course this is something gzdoom does 💀

shadowmap lights that don't hit one-sided walls if raytraced lights are enabled
